version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
      - image: circleci/postgres:11.3
    executor: ruby/default
    steps:
      - checkout
      - run: gem install bundler:2.0.2
      - run: bundle install
  test:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
      - image: circleci/postgres:11.3
    steps:
      - checkout
      - run: gem install bundler:2.0.2
      - run: bundle install
      - run: bundle exec rake db:create db:schema:load
      - run: bundle exec rspec

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test
